services:
  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    image: postgres:16.4-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - 5432:${DATABASE_PORT}

volumes:
  strapi-data:
